### ISSUE TITLE
Rework structure

### ISSUE THREAD

**Issue by Willem-Jaap** [pixel-perfect-agency/next-foundation#5]
The current implementations works and scales, but after looking through other codebases I think we can make this better.

https://nextjs.org/docs/app/building-your-application/routing/colocation

```[tasklist]
### Tasks
- [x] remove core folder
- [x] add components/hooks/styles to src folder
- [x] use tailwind
- [ ] tailwind cn utility with clsx + tailwind-merge
```
